In [23]:
def division(a,b):
    try:
        result = a/b
        print("Yeah ! Your answer is :", result) 
    except ZeroDivisionError: 
        print("Sorry ! You are dividing by zero ") 
  
division(5,0)
division(5,2)
    
    

Sorry ! You are dividing by zero 
Yeah ! Your answer is : 2.5


In [24]:
subjects=["Americans", "Indians"]
verbs=["play", "watch"]
objects=["baseball","cricket"]

# Use list comprehension instead of looping over each of the predicates
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subjects for vb in verbs for ob in objects]
for sentence in sentence_list:
 print (sentence)

Americans play baseball
Americans play cricket
Americans watch baseball
Americans watch cricket
Indians play baseball
Indians play cricket
Indians watch baseball
Indians watch cricket


In [25]:
#For increasing = FALSE , with VAnder function
import numpy as np
x = np.array([1, 2, 3, 5])
N = 6
np.vander(x, N)


array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [3125,  625,  125,   25,    5,    1]])

In [26]:
#For increasing = FALSE , with for loop
import numpy as np
x = np.array([1, 2, 3, 5])
N = 6
#For increasing = False
np.column_stack([x**(N-1-i) for i in range(N)])

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [3125,  625,  125,   25,    5,    1]])

In [27]:
#For increasing = TRUE , with VAnder function
import numpy as np
x = np.array([1, 2, 3, 5])
N = 6
np.vander(x, N,increasing = True)

array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    5,   25,  125,  625, 3125]])

In [28]:
#For increasing = TRUE , with for loop
import numpy as np
x = np.array([1, 2, 3, 5])
N = 6
#For increasing = TRUE
np.column_stack([x**(i) for i in range(N)])

array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    5,   25,  125,  625, 3125]])